import { SQLiteDatabase } from 'expo-sqlite';

const SEED_FOODS = [
  { id: "seed-001", name: "Chicken Breast, Grilled", brand: null, barcode: null, calories: 165, protein: 31, carbs: 0, fat: 3.6, fiber: 0, sugar: 0, sodium: 74, serving_size: 100, serving_unit: "g", serving_size_grams: 100 },
  { id: "seed-002", name: "Chicken Thigh, Boneless, Skinless, Cooked", brand: null, barcode: null, calories: 179, protein: 24.8, carbs: 0, fat: 8.2, fiber: 0, sugar: 0, sodium: 84, serving_size: 100, serving_unit: "g", serving_size_grams: 100 },
  { id: "seed-003", name: "Chicken Wing, Cooked", brand: null, barcode: null, calories: 203, protein: 30.5, carbs: 0, fat: 8.1, fiber: 0, sugar: 0, sodium: 82, serving_size: 100, serving_unit: "g", serving_size_grams: 100 },
  { id: "seed-004", name: "Egg, Whole, Large", brand: null, barcode: null, calories: 72, protein: 6.3, carbs: 0.4, fat: 4.8, fiber: 0, sugar: 0.2, sodium: 71, serving_size: 1, serving_unit: "large", serving_size_grams: 50 },
  { id: "seed-005", name: "Egg White, Large", brand: null, barcode: null, calories: 17, protein: 3.6, carbs: 0.2, fat: 0.1, fiber: 0, sugar: 0.2, sodium: 55, serving_size: 1, serving_unit: "large", serving_size_grams: 33 },
  { id: "seed-006", name: "Ground Beef, 85% Lean", brand: null, barcode: null, calories: 215, protein: 18.6, carbs: 0, fat: 15, fiber: 0, sugar: 0, sodium: 66, serving_size: 100, serving_unit: "g", serving_size_grams: 100 },
  { id: "seed-007", name: "Ground Beef, 93% Lean", brand: null, barcode: null, calories: 152, protein: 21.4, carbs: 0, fat: 6.7, fiber: 0, sugar: 0, sodium: 66, serving_size: 100, serving_unit: "g", serving_size_grams: 100 },
  { id: "seed-008", name: "Beef Steak, Sirloin, Cooked", brand: null, barcode: null, calories: 183, protein: 27.2, carbs: 0, fat: 7.4, fiber: 0, sugar: 0, sodium: 56, serving_size: 100, serving_unit: "g", serving_size_grams: 100 },
  { id: "seed-009", name: "Pork Chop, Boneless, Cooked", brand: null, barcode: null, calories: 197, protein: 25.7, carbs: 0, fat: 9.7, fiber: 0, sugar: 0, sodium: 62, serving_size: 100, serving_unit: "g", serving_size_grams: 100 },
  { id: "seed-010", name: "Bacon, Cooked", brand: null, barcode: null, calories: 541, protein: 37, carbs: 1.4, fat: 42, fiber: 0, sugar: 0, sodium: 1717, serving_size: 100, serving_unit: "g", serving_size_grams: 100 },
  { id: "seed-011", name: "Turkey Breast, Roasted", brand: null, barcode: null, calories: 135, protein: 30.1, carbs: 0, fat: 0.7, fiber: 0, sugar: 0, sodium: 46, serving_size: 100, serving_unit: "g", serving_size_grams: 100 },
  { id: "seed-012", name: "Ground Turkey, 93% Lean", brand: null, barcode: null, calories: 149, protein: 19.4, carbs: 0, fat: 7.7, fiber: 0, sugar: 0, sodium: 88, serving_size: 100, serving_unit: "g", serving_size_grams: 100 },
  { id: "seed-013", name: "Salmon, Atlantic, Wild, Cooked", brand: null, barcode: null, calories: 182, protein: 25.4, carbs: 0, fat: 8.1, fiber: 0, sugar: 0, sodium: 56, serving_size: 100, serving_unit: "g", serving_size_grams: 100 },
  { id: "seed-014", name: "Salmon, Atlantic, Farmed, Cooked", brand: null, barcode: null, calories: 206, protein: 22.1, carbs: 0, fat: 12.4, fiber: 0, sugar: 0, sodium: 59, serving_size: 100, serving_unit: "g", serving_size_grams: 100 },
  { id: "seed-015", name: "Tuna, Canned in Water, Drained", brand: null, barcode: null, calories: 116, protein: 25.5, carbs: 0, fat: 0.8, fiber: 0, sugar: 0, sodium: 338, serving_size: 100, serving_unit: "g", serving_size_grams: 100 },
  { id: "seed-016", name: "Shrimp, Cooked", brand: null, barcode: null, calories: 99, protein: 24, carbs: 0.2, fat: 0.3, fiber: 0, sugar: 0, sodium: 111, serving_size: 100, serving_unit: "g", serving_size_grams: 100 },
  { id: "seed-017", name: "Tilapia, Cooked", brand: null, barcode: null, calories: 128, protein: 26.2, carbs: 0, fat: 2.7, fiber: 0, sugar: 0, sodium: 56, serving_size: 100, serving_unit: "g", serving_size_grams: 100 },
  { id: "seed-018", name: "Cod, Cooked", brand: null, barcode: null, calories: 105, protein: 23, carbs: 0, fat: 0.9, fiber: 0, sugar: 0, sodium: 78, serving_size: 100, serving_unit: "g", serving_size_grams: 100 },
  { id: "seed-019", name: "Tofu, Firm", brand: null, barcode: null, calories: 144, protein: 17.3, carbs: 2.8, fat: 8.7, fiber: 2.3, sugar: 0.6, sodium: 14, serving_size: 100, serving_unit: "g", serving_size_grams: 100 },
  { id: "seed-020", name: "Tempeh", brand: null, barcode: null, calories: 192, protein: 20.3, carbs: 7.6, fat: 10.8, fiber: 0, sugar: 0, sodium: 9, serving_size: 100, serving_unit: "g", serving_size_grams: 100 },
  { id: "seed-021", name: "Black Beans, Cooked", brand: null, barcode: null, calories: 132, protein: 8.9, carbs: 23.7, fat: 0.5, fiber: 8.7, sugar: 0.3, sodium: 1, serving_size: 100, serving_unit: "g", serving_size_grams: 100 },
  { id: "seed-022", name: "Chickpeas, Cooked", brand: null, barcode: null, calories: 164, protein: 8.9, carbs: 27.4, fat: 2.6, fiber: 7.6, sugar: 4.8, sodium: 7, serving_size: 100, serving_unit: "g", serving_size_grams: 100 },
  { id: "seed-023", name: "Lentils, Cooked", brand: null, barcode: null, calories: 116, protein: 9, carbs: 20.1, fat: 0.4, fiber: 7.9, sugar: 1.8, sodium: 2, serving_size: 100, serving_unit: "g", serving_size_grams: 100 },
  { id: "seed-024", name: "Banana, Medium", brand: null, barcode: null, calories: 105, protein: 1.3, carbs: 27, fat: 0.4, fiber: 3.1, sugar: 14.4, sodium: 1, serving_size: 1, serving_unit: "medium", serving_size_grams: 118 },
  { id: "seed-025", name: "Apple, Medium", brand: null, barcode: null, calories: 95, protein: 0.5, carbs: 25, fat: 0.3, fiber: 4.4, sugar: 19, sodium: 2, serving_size: 1, serving_unit: "medium", serving_size_grams: 182 },
  { id: "seed-026", name: "Orange, Medium", brand: null, barcode: null, calories: 62, protein: 1.2, carbs: 15.4, fat: 0.2, fiber: 3.1, sugar: 12.2, sodium: 0, serving_size: 1, serving_unit: "medium", serving_size_grams: 131 },
  { id: "seed-027", name: "Strawberries, Fresh", brand: null, barcode: null, calories: 32, protein: 0.7, carbs: 7.7, fat: 0.3, fiber: 2, sugar: 4.9, sodium: 1, serving_size: 100, serving_unit: "g", serving_size_grams: 100 },
  { id: "seed-028", name: "Blueberries, Fresh", brand: null, barcode: null, calories: 57, protein: 0.7, carbs: 14.5, fat: 0.3, fiber: 2.4, sugar: 10, sodium: 1, serving_size: 100, serving_unit: "g", serving_size_grams: 100 },
  { id: "seed-029", name: "Raspberries, Fresh", brand: null, barcode: null, calories: 52, protein: 1.2, carbs: 11.9, fat: 0.7, fiber: 6.5, sugar: 4.4, sodium: 1, serving_size: 100, serving_unit: "g", serving_size_grams: 100 },
  { id: "seed-030", name: "Grapes, Red or Green", brand: null, barcode: null, calories: 69, protein: 0.7, carbs: 18.1, fat: 0.2, fiber: 0.9, sugar: 15.5, sodium: 2, serving_size: 100, serving_unit: "g", serving_size_grams: 100 },
  { id: "seed-031", name: "Watermelon", brand: null, barcode: null, calories: 30, protein: 0.6, carbs: 7.6, fat: 0.2, fiber: 0.4, sugar: 6.2, sodium: 1, serving_size: 100, serving_unit: "g", serving_size_grams: 100 },
  { id: "seed-032", name: "Mango", brand: null, barcode: null, calories: 60, protein: 0.8, carbs: 15, fat: 0.4, fiber: 1.6, sugar: 13.7, sodium: 1, serving_size: 100, serving_unit: "g", serving_size_grams: 100 },
  { id: "seed-033", name: "Pineapple", brand: null, barcode: null, calories: 50, protein: 0.5, carbs: 13.1, fat: 0.1, fiber: 1.4, sugar: 9.9, sodium: 1, serving_size: 100, serving_unit: "g", serving_size_grams: 100 },
  { id: "seed-034", name: "Avocado", brand: null, barcode: null, calories: 160, protein: 2, carbs: 8.5, fat: 14.7, fiber: 6.7, sugar: 0.7, sodium: 7, serving_size: 100, serving_unit: "g", serving_size_grams: 100 },
  { id: "seed-035", name: "Peach, Medium", brand: null, barcode: null, calories: 59, protein: 1.4, carbs: 14.3, fat: 0.4, fiber: 2.3, sugar: 12.4, sodium: 0, serving_size: 1, serving_unit: "medium", serving_size_grams: 150 },
  { id: "seed-036", name: "Broccoli, Raw", brand: null, barcode: null, calories: 34, protein: 2.8, carbs: 6.6, fat: 0.4, fiber: 2.6, sugar: 1.7, sodium: 33, serving_size: 100, serving_unit: "g", serving_size_grams: 100 },
  { id: "seed-037", name: "Broccoli, Steamed", brand: null, barcode: null, calories: 35, protein: 2.4, carbs: 7.2, fat: 0.4, fiber: 3.3, sugar: 1.4, sodium: 41, serving_size: 100, serving_unit: "g", serving_size_grams: 100 },
  { id: "seed-038", name: "Spinach, Raw", brand: null, barcode: null, calories: 23, protein: 2.9, carbs: 3.6, fat: 0.4, fiber: 2.2, sugar: 0.4, sodium: 79, serving_size: 100, serving_unit: "g", serving_size_grams: 100 },
  { id: "seed-039", name: "Kale, Raw", brand: null, barcode: null, calories: 43, protein: 2.9, carbs: 4.4, fat: 1.5, fiber: 4.1, sugar: 0.8, sodium: 53, serving_size: 100, serving_unit: "g", serving_size_grams: 100 },
  { id: "seed-040", name: "Carrots, Raw", brand: null, barcode: null, calories: 41, protein: 0.9, carbs: 9.6, fat: 0.2, fiber: 2.8, sugar: 4.7, sodium: 69, serving_size: 100, serving_unit: "g", serving_size_grams: 100 },
  { id: "seed-041", name: "Bell Pepper, Red", brand: null, barcode: null, calories: 31, protein: 1, carbs: 6, fat: 0.3, fiber: 2.1, sugar: 4.2, sodium: 4, serving_size: 100, serving_unit: "g", serving_size_grams: 100 },
  { id: "seed-042", name: "Cucumber", brand: null, barcode: null, calories: 15, protein: 0.7, carbs: 3.6, fat: 0.1, fiber: 0.5, sugar: 1.7, sodium: 2, serving_size: 100, serving_unit: "g", serving_size_grams: 100 },
  { id: "seed-043", name: "Tomato, Raw", brand: null, barcode: null, calories: 18, protein: 0.9, carbs: 3.9, fat: 0.2, fiber: 1.2, sugar: 2.6, sodium: 5, serving_size: 100, serving_unit: "g", serving_size_grams: 100 },
  { id: "seed-044", name: "Sweet Potato, Baked", brand: null, barcode: null, calories: 90, protein: 2, carbs: 20.7, fat: 0.1, fiber: 3.3, sugar: 6.5, sodium: 36, serving_size: 100, serving_unit: "g", serving_size_grams: 100 },
  { id: "seed-045", name: "Potato, Baked with Skin", brand: null, barcode: null, calories: 93, protein: 2.5, carbs: 21.2, fat: 0.1, fiber: 2.2, sugar: 1.2, sodium: 10, serving_size: 100, serving_unit: "g", serving_size_grams: 100 },
  { id: "seed-046", name: "Asparagus, Cooked", brand: null, barcode: null, calories: 22, protein: 2.4, carbs: 4.1, fat: 0.2, fiber: 2, sugar: 1.3, sodium: 14, serving_size: 100, serving_unit: "g", serving_size_grams: 100 },
  { id: "seed-047", name: "Green Beans, Cooked", brand: null, barcode: null, calories: 35, protein: 1.9, carbs: 7.9, fat: 0.3, fiber: 3.2, sugar: 1.6, sodium: 1, serving_size: 100, serving_unit: "g", serving_size_grams: 100 },
  { id: "seed-048", name: "Cauliflower, Raw", brand: null, barcode: null, calories: 25, protein: 1.9, carbs: 5, fat: 0.3, fiber: 2, sugar: 1.9, sodium: 30, serving_size: 100, serving_unit: "g", serving_size_grams: 100 },
  { id: "seed-049", name: "Zucchini, Raw", brand: null, barcode: null, calories: 17, protein: 1.2, carbs: 3.1, fat: 0.3, fiber: 1, sugar: 2.5, sodium: 8, serving_size: 100, serving_unit: "g", serving_size_grams: 100 },
  { id: "seed-050", name: "Mushrooms, White, Raw", brand: null, barcode: null, calories: 22, protein: 3.1, carbs: 3.3, fat: 0.3, fiber: 1, sugar: 2, sodium: 5, serving_size: 100, serving_unit: "g", serving_size_grams: 100 },
  { id: "seed-051", name: "Onion, Raw", brand: null, barcode: null, calories: 40, protein: 1.1, carbs: 9.3, fat: 0.1, fiber: 1.7, sugar: 4.2, sodium: 4, serving_size: 100, serving_unit: "g", serving_size_grams: 100 },
  { id: "seed-052", name: "Celery, Raw", brand: null, barcode: null, calories: 14, protein: 0.7, carbs: 3, fat: 0.2, fiber: 1.6, sugar: 1.3, sodium: 80, serving_size: 100, serving_unit: "g", serving_size_grams: 100 },
  { id: "seed-053", name: "White Rice, Cooked", brand: null, barcode: null, calories: 130, protein: 2.7, carbs: 28.2, fat: 0.3, fiber: 0.4, sugar: 0, sodium: 1, serving_size: 100, serving_unit: "g", serving_size_grams: 100 },
  { id: "seed-054", name: "Brown Rice, Cooked", brand: null, barcode: null, calories: 112, protein: 2.3, carbs: 23.5, fat: 0.8, fiber: 1.8, sugar: 0.4, sodium: 1, serving_size: 100, serving_unit: "g", serving_size_grams: 100 },
  { id: "seed-055", name: "Quinoa, Cooked", brand: null, barcode: null, calories: 120, protein: 4.4, carbs: 21.3, fat: 1.9, fiber: 2.8, sugar: 0.9, sodium: 7, serving_size: 100, serving_unit: "g", serving_size_grams: 100 },
  { id: "seed-056", name: "Oatmeal, Cooked", brand: null, barcode: null, calories: 68, protein: 2.4, carbs: 12, fat: 1.4, fiber: 1.7, sugar: 0.3, sodium: 49, serving_size: 100, serving_unit: "g", serving_size_grams: 100 },
  { id: "seed-057", name: "Oats, Rolled, Dry", brand: null, barcode: null, calories: 379, protein: 13.2, carbs: 67.7, fat: 6.5, fiber: 10.1, sugar: 1, sodium: 6, serving_size: 100, serving_unit: "g", serving_size_grams: 100 },
  { id: "seed-058", name: "Pasta, Cooked", brand: null, barcode: null, calories: 131, protein: 5, carbs: 25, fat: 1.1, fiber: 1.8, sugar: 0.6, sodium: 1, serving_size: 100, serving_unit: "g", serving_size_grams: 100 },
  { id: "seed-059", name: "Whole Wheat Bread", brand: null, barcode: null, calories: 247, protein: 13, carbs: 41, fat: 4.2, fiber: 6, sugar: 6, sodium: 472, serving_size: 100, serving_unit: "g", serving_size_grams: 100 },
  { id: "seed-060", name: "White Bread", brand: null, barcode: null, calories: 265, protein: 9.4, carbs: 49, fat: 3.2, fiber: 2.7, sugar: 5, sodium: 491, serving_size: 100, serving_unit: "g", serving_size_grams: 100 },
  { id: "seed-061", name: "Tortilla, Flour (8 inch)", brand: null, barcode: null, calories: 150, protein: 4, carbs: 25, fat: 3.5, fiber: 1, sugar: 1, sodium: 340, serving_size: 1, serving_unit: "tortilla", serving_size_grams: 49 },
  { id: "seed-062", name: "Tortilla, Corn", brand: null, barcode: null, calories: 52, protein: 1.4, carbs: 10.7, fat: 0.7, fiber: 1.5, sugar: 0.2, sodium: 11, serving_size: 1, serving_unit: "tortilla", serving_size_grams: 24 },
  { id: "seed-063", name: "Greek Yogurt, Plain, Nonfat", brand: null, barcode: null, calories: 59, protein: 10.2, carbs: 3.6, fat: 0.4, fiber: 0, sugar: 3.2, sodium: 36, serving_size: 100, serving_unit: "g", serving_size_grams: 100 },
  { id: "seed-064", name: "Greek Yogurt, Plain, Whole Milk", brand: null, barcode: null, calories: 97, protein: 9, carbs: 3.9, fat: 5, fiber: 0, sugar: 3.8, sodium: 47, serving_size: 100, serving_unit: "g", serving_size_grams: 100 },
  { id: "seed-065", name: "Cottage Cheese, Low Fat (2%)", brand: null, barcode: null, calories: 84, protein: 11.1, carbs: 3.4, fat: 2.3, fiber: 0, sugar: 3.2, sodium: 329, serving_size: 100, serving_unit: "g", serving_size_grams: 100 },
  { id: "seed-066", name: "Milk, Whole", brand: null, barcode: null, calories: 61, protein: 3.2, carbs: 4.8, fat: 3.3, fiber: 0, sugar: 5, sodium: 43, serving_size: 100, serving_unit: "ml", serving_size_grams: 100 },
  { id: "seed-067", name: "Milk, 2% Reduced Fat", brand: null, barcode: null, calories: 50, protein: 3.3, carbs: 4.8, fat: 2, fiber: 0, sugar: 5.1, sodium: 41, serving_size: 100, serving_unit: "ml", serving_size_grams: 100 },
  { id: "seed-068", name: "Milk, Skim (Nonfat)", brand: null, barcode: null, calories: 34, protein: 3.4, carbs: 5, fat: 0.1, fiber: 0, sugar: 5.1, sodium: 42, serving_size: 100, serving_unit: "ml", serving_size_grams: 100 },
  { id: "seed-069", name: "Almond Milk, Unsweetened", brand: null, barcode: null, calories: 15, protein: 0.6, carbs: 0.6, fat: 1.2, fiber: 0, sugar: 0, sodium: 72, serving_size: 100, serving_unit: "ml", serving_size_grams: 100 },
  { id: "seed-070", name: "Oat Milk, Unsweetened", brand: null, barcode: null, calories: 40, protein: 1, carbs: 7, fat: 1.5, fiber: 0.5, sugar: 0, sodium: 36, serving_size: 100, serving_unit: "ml", serving_size_grams: 100 },
  { id: "seed-071", name: "Cheddar Cheese", brand: null, barcode: null, calories: 403, protein: 24.9, carbs: 1.3, fat: 33.1, fiber: 0, sugar: 0.5, sodium: 621, serving_size: 100, serving_unit: "g", serving_size_grams: 100 },
  { id: "seed-072", name: "Mozzarella Cheese, Part Skim", brand: null, barcode: null, calories: 254, protein: 24.3, carbs: 2.8, fat: 15.9, fiber: 0, sugar: 1.1, sodium: 619, serving_size: 100, serving_unit: "g", serving_size_grams: 100 },
  { id: "seed-073", name: "Parmesan Cheese, Grated", brand: null, barcode: null, calories: 431, protein: 38.5, carbs: 4.1, fat: 28.6, fiber: 0, sugar: 0.9, sodium: 1529, serving_size: 100, serving_unit: "g", serving_size_grams: 100 },
  { id: "seed-074", name: "Cream Cheese", brand: null, barcode: null, calories: 342, protein: 5.9, carbs: 4.1, fat: 34.2, fiber: 0, sugar: 3.8, sodium: 321, serving_size: 100, serving_unit: "g", serving_size_grams: 100 },
  { id: "seed-075", name: "Feta Cheese", brand: null, barcode: null, calories: 264, protein: 14.2, carbs: 4.1, fat: 21.3, fiber: 0, sugar: 4.1, sodium: 1116, serving_size: 100, serving_unit: "g", serving_size_grams: 100 },
  { id: "seed-076", name: "Almonds", brand: null, barcode: null, calories: 579, protein: 21.2, carbs: 21.6, fat: 49.9, fiber: 12.5, sugar: 4.4, sodium: 1, serving_size: 100, serving_unit: "g", serving_size_grams: 100 },
  { id: "seed-077", name: "Peanuts, Dry Roasted", brand: null, barcode: null, calories: 585, protein: 23.7, carbs: 21.5, fat: 49.7, fiber: 8, sugar: 4.2, sodium: 6, serving_size: 100, serving_unit: "g", serving_size_grams: 100 },
  { id: "seed-078", name: "Walnuts", brand: null, barcode: null, calories: 654, protein: 15.2, carbs: 13.7, fat: 65.2, fiber: 6.7, sugar: 2.6, sodium: 2, serving_size: 100, serving_unit: "g", serving_size_grams: 100 },
  { id: "seed-079", name: "Cashews", brand: null, barcode: null, calories: 553, protein: 18.2, carbs: 30.2, fat: 43.9, fiber: 3.3, sugar: 5.9, sodium: 12, serving_size: 100, serving_unit: "g", serving_size_grams: 100 },
  { id: "seed-080", name: "Peanut Butter", brand: null, barcode: null, calories: 588, protein: 25.1, carbs: 20, fat: 50.4, fiber: 6, sugar: 9.2, sodium: 426, serving_size: 100, serving_unit: "g", serving_size_grams: 100 },
  { id: "seed-081", name: "Almond Butter", brand: null, barcode: null, calories: 614, protein: 21, carbs: 18.8, fat: 55.5, fiber: 10.3, sugar: 4.4, sodium: 7, serving_size: 100, serving_unit: "g", serving_size_grams: 100 },
  { id: "seed-082", name: "Olive Oil", brand: null, barcode: null, calories: 884, protein: 0, carbs: 0, fat: 100, fiber: 0, sugar: 0, sodium: 2, serving_size: 1, serving_unit: "tbsp", serving_size_grams: 14 },
  { id: "seed-083", name: "Coconut Oil", brand: null, barcode: null, calories: 862, protein: 0, carbs: 0, fat: 100, fiber: 0, sugar: 0, sodium: 0, serving_size: 1, serving_unit: "tbsp", serving_size_grams: 14 },
  { id: "seed-084", name: "Butter", brand: null, barcode: null, calories: 717, protein: 0.9, carbs: 0.1, fat: 81.1, fiber: 0, sugar: 0.1, sodium: 576, serving_size: 1, serving_unit: "tbsp", serving_size_grams: 14 },
  { id: "seed-085", name: "Honey", brand: null, barcode: null, calories: 304, protein: 0.3, carbs: 82.4, fat: 0, fiber: 0.2, sugar: 82.1, sodium: 4, serving_size: 1, serving_unit: "tbsp", serving_size_grams: 21 },
  { id: "seed-086", name: "Maple Syrup", brand: null, barcode: null, calories: 260, protein: 0, carbs: 67, fat: 0.1, fiber: 0, sugar: 60.5, sodium: 12, serving_size: 1, serving_unit: "tbsp", serving_size_grams: 20 },
  { id: "seed-087", name: "Hummus", brand: null, barcode: null, calories: 166, protein: 7.9, carbs: 14.3, fat: 9.6, fiber: 6, sugar: 0.3, sodium: 379, serving_size: 100, serving_unit: "g", serving_size_grams: 100 },
  { id: "seed-088", name: "Guacamole", brand: null, barcode: null, calories: 157, protein: 2, carbs: 8.5, fat: 14.3, fiber: 6, sugar: 0.5, sodium: 375, serving_size: 100, serving_unit: "g", serving_size_grams: 100 },
  { id: "seed-089", name: "Salsa", brand: null, barcode: null, calories: 36, protein: 2, carbs: 7.1, fat: 0.2, fiber: 2.4, sugar: 4, sodium: 560, serving_size: 100, serving_unit: "g", serving_size_grams: 100 },
  { id: "seed-090", name: "Pizza, Cheese (1 slice)", brand: null, barcode: null, calories: 285, protein: 12.2, carbs: 35.7, fat: 10.4, fiber: 2.5, sugar: 3.6, sodium: 640, serving_size: 1, serving_unit: "slice", serving_size_grams: 107 },
  { id: "seed-091", name: "Hamburger (Single Patty with Bun)", brand: null, barcode: null, calories: 295, protein: 17, carbs: 24, fat: 14, fiber: 1.3, sugar: 5, sodium: 495, serving_size: 1, serving_unit: "sandwich", serving_size_grams: 110 },
  { id: "seed-092", name: "Hot Dog with Bun", brand: null, barcode: null, calories: 290, protein: 11, carbs: 24, fat: 17, fiber: 0.8, sugar: 4, sodium: 810, serving_size: 1, serving_unit: "hot dog", serving_size_grams: 98 },
  { id: "seed-093", name: "Burrito, Beef and Bean", brand: null, barcode: null, calories: 206, protein: 7.6, carbs: 26, fat: 7.7, fiber: 4.6, sugar: 1.2, sodium: 495, serving_size: 100, serving_unit: "g", serving_size_grams: 100 },
  { id: "seed-094", name: "Taco, Beef", brand: null, barcode: null, calories: 210, protein: 9.5, carbs: 20.7, fat: 10.1, fiber: 2.5, sugar: 2.1, sodium: 571, serving_size: 1, serving_unit: "taco", serving_size_grams: 80 },
  { id: "seed-095", name: "Sushi Roll, California", brand: null, barcode: null, calories: 255, protein: 9, carbs: 38, fat: 7, fiber: 5.8, sugar: 9.8, sodium: 575, serving_size: 1, serving_unit: "roll", serving_size_grams: 180 },
  { id: "seed-096", name: "French Fries", brand: null, barcode: null, calories: 312, protein: 3.4, carbs: 41, fat: 15, fiber: 3.8, sugar: 0.3, sodium: 210, serving_size: 100, serving_unit: "g", serving_size_grams: 100 },
  { id: "seed-097", name: "Chicken Nuggets", brand: null, barcode: null, calories: 296, protein: 15.8, carbs: 16.3, fat: 19, fiber: 0.9, sugar: 0.5, sodium: 545, serving_size: 100, serving_unit: "g", serving_size_grams: 100 },
  { id: "seed-098", name: "Fried Rice", brand: null, barcode: null, calories: 163, protein: 4.3, carbs: 25, fat: 5.2, fiber: 1.5, sugar: 0.9, sodium: 520, serving_size: 100, serving_unit: "g", serving_size_grams: 100 },
  { id: "seed-099", name: "Pad Thai with Chicken", brand: null, barcode: null, calories: 166, protein: 10.7, carbs: 18.3, fat: 5.5, fiber: 1.8, sugar: 4.5, sodium: 546, serving_size: 100, serving_unit: "g", serving_size_grams: 100 },
  { id: "seed-100", name: "Macaroni and Cheese", brand: null, barcode: null, calories: 164, protein: 6.4, carbs: 18.4, fat: 7.2, fiber: 0.8, sugar: 2.2, sodium: 459, serving_size: 100, serving_unit: "g", serving_size_grams: 100 },
  { id: "seed-101", name: "Lasagna with Meat", brand: null, barcode: null, calories: 135, protein: 8.2, carbs: 13.1, fat: 5.4, fiber: 1.4, sugar: 2.5, sodium: 350, serving_size: 100, serving_unit: "g", serving_size_grams: 100 },
  { id: "seed-102", name: "Chicken Salad", brand: null, barcode: null, calories: 208, protein: 17, carbs: 1.5, fat: 15, fiber: 0.3, sugar: 0.9, sodium: 280, serving_size: 100, serving_unit: "g", serving_size_grams: 100 },
  { id: "seed-103", name: "Caesar Salad with Chicken", brand: null, barcode: null, calories: 127, protein: 10.7, carbs: 5.1, fat: 7.2, fiber: 1.7, sugar: 1.1, sodium: 312, serving_size: 100, serving_unit: "g", serving_size_grams: 100 },
  { id: "seed-104", name: "Protein Shake (Whey, Water)", brand: null, barcode: null, calories: 120, protein: 24, carbs: 3, fat: 1.5, fiber: 0, sugar: 2, sodium: 150, serving_size: 1, serving_unit: "scoop", serving_size_grams: 32 },
  { id: "seed-105", name: "Protein Bar", brand: null, barcode: null, calories: 200, protein: 20, carbs: 22, fat: 7, fiber: 5, sugar: 5, sodium: 200, serving_size: 1, serving_unit: "bar", serving_size_grams: 60 },
  { id: "seed-106", name: "Granola", brand: null, barcode: null, calories: 489, protein: 14.5, carbs: 53.4, fat: 24.4, fiber: 8.6, sugar: 20.7, sodium: 26, serving_size: 100, serving_unit: "g", serving_size_grams: 100 },
  { id: "seed-107", name: "Trail Mix", brand: null, barcode: null, calories: 462, protein: 13.8, carbs: 44.5, fat: 28.3, fiber: 4.2, sugar: 25.5, sodium: 256, serving_size: 100, serving_unit: "g", serving_size_grams: 100 },
  { id: "seed-108", name: "Dark Chocolate (70-85%)", brand: null, barcode: null, calories: 598, protein: 7.8, carbs: 45.9, fat: 42.6, fiber: 10.9, sugar: 24, sodium: 20, serving_size: 100, serving_unit: "g", serving_size_grams: 100 },
  { id: "seed-109", name: "Ice Cream, Vanilla", brand: null, barcode: null, calories: 207, protein: 3.5, carbs: 23.6, fat: 11, fiber: 0.7, sugar: 21.2, sodium: 80, serving_size: 100, serving_unit: "g", serving_size_grams: 100 },
  { id: "seed-110", name: "Banana Bread (1 slice)", brand: null, barcode: null, calories: 326, protein: 4.3, carbs: 53.2, fat: 10.5, fiber: 0.7, sugar: 28.4, sodium: 181, serving_size: 1, serving_unit: "slice", serving_size_grams: 60 },
  { id: "seed-111", name: "Brownie", brand: null, barcode: null, calories: 466, protein: 5.7, carbs: 60.6, fat: 22.8, fiber: 2.3, sugar: 40.4, sodium: 250, serving_size: 100, serving_unit: "g", serving_size_grams: 100 },
  { id: "seed-112", name: "Chocolate Chip Cookie", brand: null, barcode: null, calories: 488, protein: 5.1, carbs: 64.3, fat: 23.5, fiber: 2.4, sugar: 36.7, sodium: 335, serving_size: 100, serving_unit: "g", serving_size_grams: 100 },
  { id: "seed-113", name: "Pancakes (plain)", brand: null, barcode: null, calories: 227, protein: 6.4, carbs: 28.4, fat: 9.8, fiber: 1.1, sugar: 5.3, sodium: 439, serving_size: 100, serving_unit: "g", serving_size_grams: 100 },
  { id: "seed-114", name: "Waffle, Plain", brand: null, barcode: null, calories: 291, protein: 7.9, carbs: 32.9, fat: 14.1, fiber: 1.7, sugar: 4.8, sodium: 511, serving_size: 100, serving_unit: "g", serving_size_grams: 100 },
  { id: "seed-115", name: "Bagel, Plain", brand: null, barcode: null, calories: 250, protein: 10, carbs: 48, fat: 1.5, fiber: 2.1, sugar: 5.5, sodium: 430, serving_size: 1, serving_unit: "bagel", serving_size_grams: 95 },
  { id: "seed-116", name: "Croissant", brand: null, barcode: null, calories: 406, protein: 8.2, carbs: 45.8, fat: 21, fiber: 2.6, sugar: 11.3, sodium: 398, serving_size: 100, serving_unit: "g", serving_size_grams: 100 },
  { id: "seed-117", name: "Muffin, Blueberry", brand: null, barcode: null, calories: 377, protein: 6.5, carbs: 53, fat: 15.4, fiber: 2.5, sugar: 29.3, sodium: 447, serving_size: 100, serving_unit: "g", serving_size_grams: 100 },
  { id: "seed-118", name: "Orange Juice", brand: null, barcode: null, calories: 45, protein: 0.7, carbs: 10.4, fat: 0.2, fiber: 0.2, sugar: 8.4, sodium: 1, serving_size: 100, serving_unit: "ml", serving_size_grams: 100 },
  { id: "seed-119", name: "Apple Juice", brand: null, barcode: null, calories: 46, protein: 0.1, carbs: 11.3, fat: 0.1, fiber: 0.1, sugar: 9.6, sodium: 4, serving_size: 100, serving_unit: "ml", serving_size_grams: 100 },
  { id: "seed-120", name: "Coffee, Black", brand: null, barcode: null, calories: 2, protein: 0.3, carbs: 0, fat: 0, fiber: 0, sugar: 0, sodium: 5, serving_size: 1, serving_unit: "cup", serving_size_grams: 240 },
  { id: "seed-121", name: "Latte, Whole Milk", brand: null, barcode: null, calories: 150, protein: 8, carbs: 12, fat: 8, fiber: 0, sugar: 11, sodium: 100, serving_size: 1, serving_unit: "grande", serving_size_grams: 473 },
  { id: "seed-122", name: "Cappuccino, Whole Milk", brand: null, barcode: null, calories: 120, protein: 7, carbs: 10, fat: 6, fiber: 0, sugar: 9, sodium: 85, serving_size: 1, serving_unit: "grande", serving_size_grams: 473 },
  { id: "seed-123", name: "Tea, Green, Unsweetened", brand: null, barcode: null, calories: 1, protein: 0, carbs: 0, fat: 0, fiber: 0, sugar: 0, sodium: 1, serving_size: 1, serving_unit: "cup", serving_size_grams: 245 },
  { id: "seed-124", name: "Smoothie, Fruit", brand: null, barcode: null, calories: 54, protein: 1.1, carbs: 12.4, fat: 0.2, fiber: 0.6, sugar: 10.6, sodium: 9, serving_size: 100, serving_unit: "ml", serving_size_grams: 100 },
  { id: "seed-125", name: "Coconut Water", brand: null, barcode: null, calories: 19, protein: 0.7, carbs: 3.7, fat: 0.2, fiber: 1.1, sugar: 2.6, sodium: 105, serving_size: 100, serving_unit: "ml", serving_size_grams: 100 },
  { id: "seed-126", name: "Sports Drink (Gatorade-type)", brand: null, barcode: null, calories: 26, protein: 0, carbs: 6.5, fat: 0, fiber: 0, sugar: 6.2, sodium: 44, serving_size: 100, serving_unit: "ml", serving_size_grams: 100 },
  { id: "seed-127", name: "Beer, Regular", brand: null, barcode: null, calories: 43, protein: 0.5, carbs: 3.6, fat: 0, fiber: 0, sugar: 0, sodium: 4, serving_size: 100, serving_unit: "ml", serving_size_grams: 100 },
  { id: "seed-128", name: "Wine, Red", brand: null, barcode: null, calories: 85, protein: 0.1, carbs: 2.6, fat: 0, fiber: 0, sugar: 0.6, sodium: 4, serving_size: 100, serving_unit: "ml", serving_size_grams: 100 },
  { id: "seed-129", name: "Wine, White", brand: null, barcode: null, calories: 82, protein: 0.1, carbs: 2.6, fat: 0, fiber: 0, sugar: 1, sodium: 5, serving_size: 100, serving_unit: "ml", serving_size_grams: 100 },
  { id: "seed-130", name: "Vodka", brand: null, barcode: null, calories: 231, protein: 0, carbs: 0, fat: 0, fiber: 0, sugar: 0, sodium: 1, serving_size: 1, serving_unit: "shot", serving_size_grams: 42 },
  { id: "seed-131", name: "Soy Sauce", brand: null, barcode: null, calories: 53, protein: 8.1, carbs: 4.9, fat: 0.1, fiber: 0.8, sugar: 0.4, sodium: 5493, serving_size: 1, serving_unit: "tbsp", serving_size_grams: 16 },
  { id: "seed-132", name: "Ketchup", brand: null, barcode: null, calories: 101, protein: 1.3, carbs: 27.4, fat: 0.1, fiber: 0.3, sugar: 22.8, sodium: 907, serving_size: 1, serving_unit: "tbsp", serving_size_grams: 17 },
  { id: "seed-133", name: "Mayonnaise", brand: null, barcode: null, calories: 680, protein: 0.9, carbs: 0.6, fat: 74.9, fiber: 0, sugar: 0.6, sodium: 635, serving_size: 1, serving_unit: "tbsp", serving_size_grams: 15 },
  { id: "seed-134", name: "Mustard, Yellow", brand: null, barcode: null, calories: 66, protein: 4.4, carbs: 5.3, fat: 4, fiber: 3.3, sugar: 2.8, sodium: 1135, serving_size: 1, serving_unit: "tbsp", serving_size_grams: 16 },
  { id: "seed-135", name: "Ranch Dressing", brand: null, barcode: null, calories: 455, protein: 1.5, carbs: 6.7, fat: 47.3, fiber: 0.3, sugar: 4.7, sodium: 882, serving_size: 2, serving_unit: "tbsp", serving_size_grams: 30 },
  { id: "seed-136", name: "Italian Dressing", brand: null, barcode: null, calories: 279, protein: 0.4, carbs: 9.5, fat: 27.5, fiber: 0, sugar: 7.6, sodium: 946, serving_size: 2, serving_unit: "tbsp", serving_size_grams: 30 },
  { id: "seed-137", name: "Balsamic Vinaigrette", brand: null, barcode: null, calories: 90, protein: 0, carbs: 6, fat: 7, fiber: 0, sugar: 5, sodium: 290, serving_size: 2, serving_unit: "tbsp", serving_size_grams: 30 },
  { id: "seed-138", name: "Sour Cream", brand: null, barcode: null, calories: 198, protein: 2.4, carbs: 4.6, fat: 19.4, fiber: 0, sugar: 0.3, sodium: 80, serving_size: 100, serving_unit: "g", serving_size_grams: 100 },
  { id: "seed-139", name: "Edamame, Shelled", brand: null, barcode: null, calories: 121, protein: 11.9, carbs: 8.9, fat: 5.2, fiber: 5.2, sugar: 2.2, sodium: 6, serving_size: 100, serving_unit: "g", serving_size_grams: 100 },
  { id: "seed-140", name: "Seitan", brand: null, barcode: null, calories: 370, protein: 75, carbs: 14, fat: 1.9, fiber: 0.6, sugar: 0, sodium: 65, serving_size: 100, serving_unit: "g", serving_size_grams: 100 },
  { id: "seed-141", name: "Chia Seeds", brand: null, barcode: null, calories: 486, protein: 16.5, carbs: 42.1, fat: 30.7, fiber: 34.4, sugar: 0, sodium: 16, serving_size: 1, serving_unit: "tbsp", serving_size_grams: 12 },
  { id: "seed-142", name: "Flax Seeds", brand: null, barcode: null, calories: 534, protein: 18.3, carbs: 28.9, fat: 42.2, fiber: 27.3, sugar: 1.5, sodium: 30, serving_size: 1, serving_unit: "tbsp", serving_size_grams: 10 },
  { id: "seed-143", name: "Sunflower Seeds", brand: null, barcode: null, calories: 584, protein: 20.8, carbs: 20, fat: 51.5, fiber: 8.6, sugar: 2.6, sodium: 9, serving_size: 100, serving_unit: "g", serving_size_grams: 100 },
  { id: "seed-144", name: "Pumpkin Seeds", brand: null, barcode: null, calories: 559, protein: 30.2, carbs: 10.7, fat: 49.1, fiber: 6, sugar: 1.4, sodium: 7, serving_size: 100, serving_unit: "g", serving_size_grams: 100 },
  { id: "seed-145", name: "Dried Cranberries", brand: null, barcode: null, calories: 308, protein: 0.1, carbs: 82.4, fat: 1.4, fiber: 5.7, sugar: 72.6, sodium: 3, serving_size: 100, serving_unit: "g", serving_size_grams: 100 },
  { id: "seed-146", name: "Raisins", brand: null, barcode: null, calories: 299, protein: 3.1, carbs: 79.2, fat: 0.5, fiber: 3.7, sugar: 59.2, sodium: 11, serving_size: 100, serving_unit: "g", serving_size_grams: 100 },
  { id: "seed-147", name: "Dates, Medjool", brand: null, barcode: null, calories: 277, protein: 1.8, carbs: 75, fat: 0.2, fiber: 6.7, sugar: 66.5, sodium: 1, serving_size: 1, serving_unit: "date", serving_size_grams: 24 },
  { id: "seed-148", name: "Beef Jerky", brand: null, barcode: null, calories: 410, protein: 33.2, carbs: 11, fat: 25.6, fiber: 1.8, sugar: 9, sodium: 1870, serving_size: 100, serving_unit: "g", serving_size_grams: 100 },
  { id: "seed-149", name: "Popcorn, Air-popped", brand: null, barcode: null, calories: 387, protein: 12.9, carbs: 77.9, fat: 4.5, fiber: 14.5, sugar: 0.9, sodium: 8, serving_size: 100, serving_unit: "g", serving_size_grams: 100 },
  { id: "seed-150", name: "Potato Chips", brand: null, barcode: null, calories: 536, protein: 7, carbs: 53, fat: 34.6, fiber: 4.4, sugar: 0.3, sodium: 525, serving_size: 100, serving_unit: "g", serving_size_grams: 100 },
];

export async function migration004SeedFoods(db: SQLiteDatabase): Promise<void> {
  const now = new Date().toISOString();

  // Insert seed foods using parameterized queries
  for (const food of SEED_FOODS) {
    await db.runAsync(
      `INSERT OR IGNORE INTO food_items (
        id, name, brand, barcode, calories, protein, carbs, fat,
        fiber, sugar, sodium, serving_size, serving_unit, serving_size_grams,
        source, source_id, is_verified, is_user_created,
        last_used_at, usage_count, created_at, updated_at
      ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`,
      [
        food.id,
        food.name,
        food.brand,
        food.barcode,
        food.calories,
        food.protein,
        food.carbs,
        food.fat,
        food.fiber,
        food.sugar,
        food.sodium,
        food.serving_size,
        food.serving_unit,
        food.serving_size_grams,
        'seed',
        null,
        1,
        0,
        null,
        0,
        now,
        now,
      ]
    );
  }

  if (__DEV__) console.log(`Inserted ${SEED_FOODS.length} seed food items.`);

  // Record migration
  await db.runAsync('INSERT INTO schema_version (version) VALUES (?)', [4]);
}
