/**
 * Types for Smart Insights Feature
 * On-device LLM insights and nutrient deficiency alerts
 */

// ============================================
// INSIGHT TYPES
// ============================================

export type InsightCategory =
  | 'macro_balance'
  | 'protein'
  | 'consistency'
  | 'pattern'
  | 'trend'
  | 'hydration'
  | 'timing'
  | 'rest';

export interface Insight {
  category: InsightCategory;
  text: string;
  icon?: string; // Emoji or icon name
}

export interface InsightsResponse {
  insights: Insight[];
}

export interface CachedInsights {
  date: string; // YYYY-MM-DD
  insights: Insight[];
  generatedAt: string; // ISO timestamp
  inputHash: string; // Hash of input data to detect changes
  source: 'llm' | 'fallback'; // Whether generated by LLM or rule-based
}

// ============================================
// INPUT DATA FOR INSIGHTS
// ============================================

export interface InsightInputData {
  // Today's data
  todayCalories: number;
  todayProtein: number;
  todayCarbs: number;
  todayFat: number;
  todayFiber: number;
  todayWater: number; // in ml
  todayMealCount: number;
  todayFoods: string[]; // List of food names logged today

  // Targets
  calorieTarget: number;
  proteinTarget: number;
  carbTarget: number;
  fatTarget: number;
  fiberTarget: number;
  waterTarget: number;

  // Trends (last 7 days)
  avgCalories7d: number;
  avgProtein7d: number;
  calorieStreak: number; // Days meeting calorie target
  proteinStreak: number; // Days meeting protein target
  loggingStreak: number; // Consecutive days with logged foods

  // User context
  userGoal: 'lose' | 'maintain' | 'gain';
  daysUsingApp: number;
}

// ============================================
// DEFICIENCY ALERT TYPES
// ============================================

export type AlertSeverity = 'notice' | 'warning' | 'concern';

export interface DeficiencyCheck {
  nutrientId: string;
  nutrientName: string;
  avgIntake7d: number;
  rdaTarget: number;
  percentage: number; // avgIntake7d / rdaTarget * 100
  severity: AlertSeverity;
  foodSuggestions: string[];
}

export interface AlertDismissal {
  nutrientId: string;
  dismissedAt: string; // ISO timestamp
  dismissType: 'acknowledged' | 'snoozed_7d' | 'permanent';
  snoozeUntil?: string; // ISO timestamp for snoozed alerts
}

// ============================================
// LLM SERVICE TYPES
// ============================================

export type LLMStatus =
  | 'not_downloaded'
  | 'downloading'
  | 'ready'
  | 'loading'
  | 'generating'
  | 'error'
  | 'unsupported';

export interface LLMDownloadProgress {
  bytesDownloaded: number;
  totalBytes: number;
  percentage: number;
  estimatedSecondsRemaining: number;
}

export interface LLMCapabilities {
  canRunLocalLLM: boolean;
  reason?: string; // Why it can't run (e.g., "Insufficient memory")
  deviceInfo?: {
    platform: string;
    osVersion: string;
    totalMemory?: number;
  };
}

// ============================================
// STORE TYPES
// ============================================

export interface InsightsStoreState {
  // Cached insights
  cachedInsights: CachedInsights | null;

  // Generation state
  isGenerating: boolean;
  lastError: string | null;

  // LLM state
  llmStatus: LLMStatus;
  downloadProgress: LLMDownloadProgress | null;
  capabilities: LLMCapabilities | null;

  // Actions
  setCachedInsights: (insights: CachedInsights) => void;
  clearCachedInsights: () => void;
  setIsGenerating: (generating: boolean) => void;
  setLastError: (error: string | null) => void;
  setLLMStatus: (status: LLMStatus) => void;
  setDownloadProgress: (progress: LLMDownloadProgress | null) => void;
  setCapabilities: (capabilities: LLMCapabilities) => void;

  // Computed
  shouldRegenerate: (inputHash: string) => boolean;
}

export interface AlertDismissalStoreState {
  // Dismissals
  dismissals: AlertDismissal[];

  // Actions
  dismissAlert: (nutrientId: string, type: AlertDismissal['dismissType']) => void;
  clearDismissal: (nutrientId: string) => void;
  clearExpiredSnoozes: () => void;

  // Computed
  isAlertDismissed: (nutrientId: string) => boolean;
  getActiveDismissals: () => AlertDismissal[];
}
